name: 'SpotBugs'
description: 'Runs SpotBugs Code Analysis - https://spotbugs.github.io/'
branding:
  icon: code
  color: white
inputs:
  spotbugs-version:
    description: 'The version of SpotBugs you would like to use. You can either specify latest to always get the newest version, or you can specify a version number like 4.5.3'
    default: 'latest'
    required: false  
  arguments:
    description: 'Command arguments to be sent to SpotBugs'
    required: false
    default: ''
  output:
    description: 'Output file name'
    required: true
  input:
    description: 'Input of what you want to analyze'
    required: true
  analyse-all-code:
    description: 'Analyze all code in the project'
    required: false
    default: 'false'
runs:
  using: "composite"
  steps: 
    - id: spotbot-analysis
      run: ${{ github.action_path }}/analyze.sh
      shell: bash
      env:
        SPOTBUGS_VERSION: ${{ inputs.spotbugs-version }}
        OUTPUT: ${{ inputs.output }}
        ARGUMENTS: ${{ inputs.arguments }}  
        INPUT: ${{ inputs.input }}